networks:
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
services:
  backend:
    build:
      context: ./Travelers_backend
    tty: true
    volumes:
#      - C:\TravelersImages:/app/uploads
      - /home/user/images:/app/uploads
    depends_on:
      - postgres
    ports:
      - 4200:4200
    networks:
      dev:
  frontend:
    build:
      context: ./Travelers_frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      dev:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
#      - C:\postgresDocker:/var/lib/postgresql/data
      - /home/user:/var/lib/postgresql/data
    networks:
      dev:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/ssl/sapphire327.ru.crt:/etc/nginx/sapphire327.ru.crt'
      - '/etc/ssl/sapphire327.ru.key:/etc/nginx/sapphire327.ru.key'
    depends_on:
      - frontend
      - backend
    networks:
      dev:
volumes:
  postgres:
  backend:
  nginx: