name: Build
on:
  push:
    branches: [main]
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{secrets.SERVER_HOST}}
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        with:
          script: |
            cd /home/user/Travelers
            git pull --recurse-submodule
#            docker compose down
#            docker compose up -d --build
